// Code generated by goctl. DO NOT EDIT.
package types

type ReqLogin struct {
	ValiCode string `json:"vali_code"`
}

type RespLogin struct {
	Token string `json:"token"`
}

type ReqUserId struct {
	Id int64 `path:"id"`
}

type User struct {
	Avatar   string `json:"avatar,optional"`
	Birthday string `json:"birthday,optional"`
	Blog     string `json:"blog,optional"`
	City     string `json:"city,optional"`
	Email    string `json:"email,optional"`
	Name     string `json:"name,optional"`
	Phone    int64  `json:"phone,optional"`
	RealName string `json:"real_name,optional"`
	Summary  string `json:"summary,optional"`
}

type CommResp struct {
	Ok    bool   `json:"ok"`
	Error string `json:"error"`
}
